language: rust
rust:
    - 1.34.2
    - stable
    - beta
    - nightly

script:
  - if [[ "$TRAVIS_RUST_VERSION" == *stable* ]]; then rustup component add rustfmt; cargo fmt --version; cargo fmt -- --check || (echo "Please reformat your code with 'cargo fmt' (version $(cargo fmt --version))"; false); fi
  - cargo build -v
  - cargo test -v
